---
apiVersion: kuberhealthy.github.io/v2
kind: HealthCheck
metadata:
  name: http-check
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 5m
  podSpec:
    spec:
      containers:
        - name: http-check
          image: kuberhealthy/http-check:sha-<short-sha>
          imagePullPolicy: IfNotPresent
          env:
            - name: CHECK_URL
              value: "https://example.com"
            - name: COUNT
              value: "10"
            - name: SECONDS
              value: "1"
            - name: PASSING_PERCENT
              value: "100"
            - name: REQUEST_TYPE
              value: "GET"
            - name: EXPECTED_STATUS_CODE
              value: "200"
      restartPolicy: Never
